/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WasteIndexRouteImport } from './routes/waste/index'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as TransfersIndexRouteImport } from './routes/transfers/index'
import { Route as TemperatureIndexRouteImport } from './routes/temperature/index'
import { Route as SuppliersIndexRouteImport } from './routes/suppliers/index'
import { Route as SupplierReturnsIndexRouteImport } from './routes/supplier-returns/index'
import { Route as StockCountIndexRouteImport } from './routes/stock-count/index'
import { Route as RecipesIndexRouteImport } from './routes/recipes/index'
import { Route as QualityIndexRouteImport } from './routes/quality/index'
import { Route as PurchaseOrdersIndexRouteImport } from './routes/purchase-orders/index'
import { Route as ProductionIndexRouteImport } from './routes/production/index'
import { Route as PricebooksIndexRouteImport } from './routes/pricebooks/index'
import { Route as PosIndexRouteImport } from './routes/pos/index'
import { Route as PaymentTermsIndexRouteImport } from './routes/payment-terms/index'
import { Route as OrdersIndexRouteImport } from './routes/orders/index'
import { Route as MenusIndexRouteImport } from './routes/menus/index'
import { Route as LocationsIndexRouteImport } from './routes/locations/index'
import { Route as LeadTimesIndexRouteImport } from './routes/lead-times/index'
import { Route as InventoryIndexRouteImport } from './routes/inventory/index'
import { Route as DeliveriesIndexRouteImport } from './routes/deliveries/index'
import { Route as CustomersIndexRouteImport } from './routes/customers/index'
import { Route as CategoriesIndexRouteImport } from './routes/categories/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AlertsIndexRouteImport } from './routes/alerts/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdjustmentsIndexRouteImport } from './routes/adjustments/index'
import { Route as StockCountMobileRouteImport } from './routes/stock-count/mobile'
import { Route as InventoryOnhandRouteImport } from './routes/inventory/onhand'
import { Route as InventoryLotsRouteImport } from './routes/inventory/lots'
import { Route as PurchasingGrIndexRouteImport } from './routes/purchasing/gr/index'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'

const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WasteIndexRoute = WasteIndexRouteImport.update({
  id: '/waste/',
  path: '/waste/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransfersIndexRoute = TransfersIndexRouteImport.update({
  id: '/transfers/',
  path: '/transfers/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemperatureIndexRoute = TemperatureIndexRouteImport.update({
  id: '/temperature/',
  path: '/temperature/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersIndexRoute = SuppliersIndexRouteImport.update({
  id: '/suppliers/',
  path: '/suppliers/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierReturnsIndexRoute = SupplierReturnsIndexRouteImport.update({
  id: '/supplier-returns/',
  path: '/supplier-returns/',
  getParentRoute: () => rootRouteImport,
} as any)
const StockCountIndexRoute = StockCountIndexRouteImport.update({
  id: '/stock-count/',
  path: '/stock-count/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIndexRoute = RecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityIndexRoute = QualityIndexRouteImport.update({
  id: '/quality/',
  path: '/quality/',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseOrdersIndexRoute = PurchaseOrdersIndexRouteImport.update({
  id: '/purchase-orders/',
  path: '/purchase-orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionIndexRoute = ProductionIndexRouteImport.update({
  id: '/production/',
  path: '/production/',
  getParentRoute: () => rootRouteImport,
} as any)
const PricebooksIndexRoute = PricebooksIndexRouteImport.update({
  id: '/pricebooks/',
  path: '/pricebooks/',
  getParentRoute: () => rootRouteImport,
} as any)
const PosIndexRoute = PosIndexRouteImport.update({
  id: '/pos/',
  path: '/pos/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentTermsIndexRoute = PaymentTermsIndexRouteImport.update({
  id: '/payment-terms/',
  path: '/payment-terms/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const MenusIndexRoute = MenusIndexRouteImport.update({
  id: '/menus/',
  path: '/menus/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsIndexRoute = LocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadTimesIndexRoute = LeadTimesIndexRouteImport.update({
  id: '/lead-times/',
  path: '/lead-times/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryIndexRoute = InventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveriesIndexRoute = DeliveriesIndexRouteImport.update({
  id: '/deliveries/',
  path: '/deliveries/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsIndexRoute = AlertsIndexRouteImport.update({
  id: '/alerts/',
  path: '/alerts/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdjustmentsIndexRoute = AdjustmentsIndexRouteImport.update({
  id: '/adjustments/',
  path: '/adjustments/',
  getParentRoute: () => rootRouteImport,
} as any)
const StockCountMobileRoute = StockCountMobileRouteImport.update({
  id: '/stock-count/mobile',
  path: '/stock-count/mobile',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryOnhandRoute = InventoryOnhandRouteImport.update({
  id: '/inventory/onhand',
  path: '/inventory/onhand',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryLotsRoute = InventoryLotsRouteImport.update({
  id: '/inventory/lots',
  path: '/inventory/lots',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasingGrIndexRoute = PurchasingGrIndexRouteImport.update({
  id: '/purchasing/gr/',
  path: '/purchasing/gr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/products': typeof ProductsRoute
  '/inventory/lots': typeof InventoryLotsRoute
  '/inventory/onhand': typeof InventoryOnhandRoute
  '/stock-count/mobile': typeof StockCountMobileRoute
  '/adjustments': typeof AdjustmentsIndexRoute
  '/admin': typeof AdminIndexRoute
  '/alerts': typeof AlertsIndexRoute
  '/auth': typeof AuthIndexRoute
  '/categories': typeof CategoriesIndexRoute
  '/customers': typeof CustomersIndexRoute
  '/deliveries': typeof DeliveriesIndexRoute
  '/inventory': typeof InventoryIndexRoute
  '/lead-times': typeof LeadTimesIndexRoute
  '/locations': typeof LocationsIndexRoute
  '/menus': typeof MenusIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/payment-terms': typeof PaymentTermsIndexRoute
  '/pos': typeof PosIndexRoute
  '/pricebooks': typeof PricebooksIndexRoute
  '/production': typeof ProductionIndexRoute
  '/purchase-orders': typeof PurchaseOrdersIndexRoute
  '/quality': typeof QualityIndexRoute
  '/recipes': typeof RecipesIndexRoute
  '/stock-count': typeof StockCountIndexRoute
  '/supplier-returns': typeof SupplierReturnsIndexRoute
  '/suppliers': typeof SuppliersIndexRoute
  '/temperature': typeof TemperatureIndexRoute
  '/transfers': typeof TransfersIndexRoute
  '/users': typeof UsersIndexRoute
  '/waste': typeof WasteIndexRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/purchasing/gr': typeof PurchasingGrIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/products': typeof ProductsRoute
  '/inventory/lots': typeof InventoryLotsRoute
  '/inventory/onhand': typeof InventoryOnhandRoute
  '/stock-count/mobile': typeof StockCountMobileRoute
  '/adjustments': typeof AdjustmentsIndexRoute
  '/admin': typeof AdminIndexRoute
  '/alerts': typeof AlertsIndexRoute
  '/auth': typeof AuthIndexRoute
  '/categories': typeof CategoriesIndexRoute
  '/customers': typeof CustomersIndexRoute
  '/deliveries': typeof DeliveriesIndexRoute
  '/inventory': typeof InventoryIndexRoute
  '/lead-times': typeof LeadTimesIndexRoute
  '/locations': typeof LocationsIndexRoute
  '/menus': typeof MenusIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/payment-terms': typeof PaymentTermsIndexRoute
  '/pos': typeof PosIndexRoute
  '/pricebooks': typeof PricebooksIndexRoute
  '/production': typeof ProductionIndexRoute
  '/purchase-orders': typeof PurchaseOrdersIndexRoute
  '/quality': typeof QualityIndexRoute
  '/recipes': typeof RecipesIndexRoute
  '/stock-count': typeof StockCountIndexRoute
  '/supplier-returns': typeof SupplierReturnsIndexRoute
  '/suppliers': typeof SuppliersIndexRoute
  '/temperature': typeof TemperatureIndexRoute
  '/transfers': typeof TransfersIndexRoute
  '/users': typeof UsersIndexRoute
  '/waste': typeof WasteIndexRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/purchasing/gr': typeof PurchasingGrIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/products': typeof ProductsRoute
  '/inventory/lots': typeof InventoryLotsRoute
  '/inventory/onhand': typeof InventoryOnhandRoute
  '/stock-count/mobile': typeof StockCountMobileRoute
  '/adjustments/': typeof AdjustmentsIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/alerts/': typeof AlertsIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/customers/': typeof CustomersIndexRoute
  '/deliveries/': typeof DeliveriesIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/lead-times/': typeof LeadTimesIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/menus/': typeof MenusIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/payment-terms/': typeof PaymentTermsIndexRoute
  '/pos/': typeof PosIndexRoute
  '/pricebooks/': typeof PricebooksIndexRoute
  '/production/': typeof ProductionIndexRoute
  '/purchase-orders/': typeof PurchaseOrdersIndexRoute
  '/quality/': typeof QualityIndexRoute
  '/recipes/': typeof RecipesIndexRoute
  '/stock-count/': typeof StockCountIndexRoute
  '/supplier-returns/': typeof SupplierReturnsIndexRoute
  '/suppliers/': typeof SuppliersIndexRoute
  '/temperature/': typeof TemperatureIndexRoute
  '/transfers/': typeof TransfersIndexRoute
  '/users/': typeof UsersIndexRoute
  '/waste/': typeof WasteIndexRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/purchasing/gr/': typeof PurchasingGrIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/products'
    | '/inventory/lots'
    | '/inventory/onhand'
    | '/stock-count/mobile'
    | '/adjustments'
    | '/admin'
    | '/alerts'
    | '/auth'
    | '/categories'
    | '/customers'
    | '/deliveries'
    | '/inventory'
    | '/lead-times'
    | '/locations'
    | '/menus'
    | '/orders'
    | '/payment-terms'
    | '/pos'
    | '/pricebooks'
    | '/production'
    | '/purchase-orders'
    | '/quality'
    | '/recipes'
    | '/stock-count'
    | '/supplier-returns'
    | '/suppliers'
    | '/temperature'
    | '/transfers'
    | '/users'
    | '/waste'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/purchasing/gr'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/products'
    | '/inventory/lots'
    | '/inventory/onhand'
    | '/stock-count/mobile'
    | '/adjustments'
    | '/admin'
    | '/alerts'
    | '/auth'
    | '/categories'
    | '/customers'
    | '/deliveries'
    | '/inventory'
    | '/lead-times'
    | '/locations'
    | '/menus'
    | '/orders'
    | '/payment-terms'
    | '/pos'
    | '/pricebooks'
    | '/production'
    | '/purchase-orders'
    | '/quality'
    | '/recipes'
    | '/stock-count'
    | '/supplier-returns'
    | '/suppliers'
    | '/temperature'
    | '/transfers'
    | '/users'
    | '/waste'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/purchasing/gr'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/products'
    | '/inventory/lots'
    | '/inventory/onhand'
    | '/stock-count/mobile'
    | '/adjustments/'
    | '/admin/'
    | '/alerts/'
    | '/auth/'
    | '/categories/'
    | '/customers/'
    | '/deliveries/'
    | '/inventory/'
    | '/lead-times/'
    | '/locations/'
    | '/menus/'
    | '/orders/'
    | '/payment-terms/'
    | '/pos/'
    | '/pricebooks/'
    | '/production/'
    | '/purchase-orders/'
    | '/quality/'
    | '/recipes/'
    | '/stock-count/'
    | '/supplier-returns/'
    | '/suppliers/'
    | '/temperature/'
    | '/transfers/'
    | '/users/'
    | '/waste/'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/purchasing/gr/'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProductsRoute: typeof ProductsRoute
  InventoryLotsRoute: typeof InventoryLotsRoute
  InventoryOnhandRoute: typeof InventoryOnhandRoute
  StockCountMobileRoute: typeof StockCountMobileRoute
  AdjustmentsIndexRoute: typeof AdjustmentsIndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AlertsIndexRoute: typeof AlertsIndexRoute
  AuthIndexRoute: typeof AuthIndexRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
  DeliveriesIndexRoute: typeof DeliveriesIndexRoute
  InventoryIndexRoute: typeof InventoryIndexRoute
  LeadTimesIndexRoute: typeof LeadTimesIndexRoute
  LocationsIndexRoute: typeof LocationsIndexRoute
  MenusIndexRoute: typeof MenusIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  PaymentTermsIndexRoute: typeof PaymentTermsIndexRoute
  PosIndexRoute: typeof PosIndexRoute
  PricebooksIndexRoute: typeof PricebooksIndexRoute
  ProductionIndexRoute: typeof ProductionIndexRoute
  PurchaseOrdersIndexRoute: typeof PurchaseOrdersIndexRoute
  QualityIndexRoute: typeof QualityIndexRoute
  RecipesIndexRoute: typeof RecipesIndexRoute
  StockCountIndexRoute: typeof StockCountIndexRoute
  SupplierReturnsIndexRoute: typeof SupplierReturnsIndexRoute
  SuppliersIndexRoute: typeof SuppliersIndexRoute
  TemperatureIndexRoute: typeof TemperatureIndexRoute
  TransfersIndexRoute: typeof TransfersIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
  WasteIndexRoute: typeof WasteIndexRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  PurchasingGrIndexRoute: typeof PurchasingGrIndexRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waste/': {
      id: '/waste/'
      path: '/waste'
      fullPath: '/waste'
      preLoaderRoute: typeof WasteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfers/': {
      id: '/transfers/'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof TransfersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/temperature/': {
      id: '/temperature/'
      path: '/temperature'
      fullPath: '/temperature'
      preLoaderRoute: typeof TemperatureIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers/': {
      id: '/suppliers/'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier-returns/': {
      id: '/supplier-returns/'
      path: '/supplier-returns'
      fullPath: '/supplier-returns'
      preLoaderRoute: typeof SupplierReturnsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock-count/': {
      id: '/stock-count/'
      path: '/stock-count'
      fullPath: '/stock-count'
      preLoaderRoute: typeof StockCountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/': {
      id: '/recipes/'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof RecipesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality/': {
      id: '/quality/'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof QualityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-orders/': {
      id: '/purchase-orders/'
      path: '/purchase-orders'
      fullPath: '/purchase-orders'
      preLoaderRoute: typeof PurchaseOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production/': {
      id: '/production/'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof ProductionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricebooks/': {
      id: '/pricebooks/'
      path: '/pricebooks'
      fullPath: '/pricebooks'
      preLoaderRoute: typeof PricebooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos/': {
      id: '/pos/'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-terms/': {
      id: '/payment-terms/'
      path: '/payment-terms'
      fullPath: '/payment-terms'
      preLoaderRoute: typeof PaymentTermsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menus/': {
      id: '/menus/'
      path: '/menus'
      fullPath: '/menus'
      preLoaderRoute: typeof MenusIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/': {
      id: '/locations/'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lead-times/': {
      id: '/lead-times/'
      path: '/lead-times'
      fullPath: '/lead-times'
      preLoaderRoute: typeof LeadTimesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/': {
      id: '/inventory/'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deliveries/': {
      id: '/deliveries/'
      path: '/deliveries'
      fullPath: '/deliveries'
      preLoaderRoute: typeof DeliveriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/': {
      id: '/categories/'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts/': {
      id: '/alerts/'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adjustments/': {
      id: '/adjustments/'
      path: '/adjustments'
      fullPath: '/adjustments'
      preLoaderRoute: typeof AdjustmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock-count/mobile': {
      id: '/stock-count/mobile'
      path: '/stock-count/mobile'
      fullPath: '/stock-count/mobile'
      preLoaderRoute: typeof StockCountMobileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/onhand': {
      id: '/inventory/onhand'
      path: '/inventory/onhand'
      fullPath: '/inventory/onhand'
      preLoaderRoute: typeof InventoryOnhandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/lots': {
      id: '/inventory/lots'
      path: '/inventory/lots'
      fullPath: '/inventory/lots'
      preLoaderRoute: typeof InventoryLotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchasing/gr/': {
      id: '/purchasing/gr/'
      path: '/purchasing/gr'
      fullPath: '/purchasing/gr'
      preLoaderRoute: typeof PurchasingGrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProductsRoute: ProductsRoute,
  InventoryLotsRoute: InventoryLotsRoute,
  InventoryOnhandRoute: InventoryOnhandRoute,
  StockCountMobileRoute: StockCountMobileRoute,
  AdjustmentsIndexRoute: AdjustmentsIndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  AlertsIndexRoute: AlertsIndexRoute,
  AuthIndexRoute: AuthIndexRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
  CustomersIndexRoute: CustomersIndexRoute,
  DeliveriesIndexRoute: DeliveriesIndexRoute,
  InventoryIndexRoute: InventoryIndexRoute,
  LeadTimesIndexRoute: LeadTimesIndexRoute,
  LocationsIndexRoute: LocationsIndexRoute,
  MenusIndexRoute: MenusIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  PaymentTermsIndexRoute: PaymentTermsIndexRoute,
  PosIndexRoute: PosIndexRoute,
  PricebooksIndexRoute: PricebooksIndexRoute,
  ProductionIndexRoute: ProductionIndexRoute,
  PurchaseOrdersIndexRoute: PurchaseOrdersIndexRoute,
  QualityIndexRoute: QualityIndexRoute,
  RecipesIndexRoute: RecipesIndexRoute,
  StockCountIndexRoute: StockCountIndexRoute,
  SupplierReturnsIndexRoute: SupplierReturnsIndexRoute,
  SuppliersIndexRoute: SuppliersIndexRoute,
  TemperatureIndexRoute: TemperatureIndexRoute,
  TransfersIndexRoute: TransfersIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
  WasteIndexRoute: WasteIndexRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  PurchasingGrIndexRoute: PurchasingGrIndexRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
